"""empty message

Revision ID: 43402c0c3ccd
Revises: 
Create Date: 2023-05-07 20:44:47.244942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43402c0c3ccd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_prod', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Products_name_prod'), 'Products', ['name_prod'], unique=True)
    op.create_table('Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('username', sa.String(length=130), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Users_name'), 'Users', ['name'], unique=False)
    op.create_index(op.f('ix_Users_username'), 'Users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Users_username'), table_name='Users')
    op.drop_index(op.f('ix_Users_name'), table_name='Users')
    op.drop_table('Users')
    op.drop_index(op.f('ix_Products_name_prod'), table_name='Products')
    op.drop_table('Products')
    # ### end Alembic commands ###
