"""empty message

Revision ID: 4bfa0735d99d
Revises: d4b39b819189
Create Date: 2023-05-13 08:44:19.119357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bfa0735d99d'
down_revision = 'd4b39b819189'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_Products_year'), ['year'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Products_year'))
        batch_op.drop_column('year')

    # ### end Alembic commands ###
