"""empty message

Revision ID: 59c81c84795b
Revises: fc8ff785e1e1
Create Date: 2023-06-03 17:07:46.684536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59c81c84795b'
down_revision = 'fc8ff785e1e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(), nullable=True))

    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.drop_column('how_much')
        batch_op.drop_column('how_many')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('how_many', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('how_much', sa.INTEGER(), autoincrement=False, nullable=True))

    with op.batch_alter_table('Products', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
