"""empty message

Revision ID: 62909c6c04c8
Revises: 
Create Date: 2023-06-02 21:59:04.081958

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '62909c6c04c8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_prod', sa.String(length=120), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('genre', sa.String(), nullable=True),
    sa.Column('producer', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('Products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Products_genre'), ['genre'], unique=False)
        batch_op.create_index(batch_op.f('ix_Products_name_prod'), ['name_prod'], unique=True)
        batch_op.create_index(batch_op.f('ix_Products_producer'), ['producer'], unique=False)
        batch_op.create_index(batch_op.f('ix_Products_year'), ['year'], unique=False)

    op.create_table('Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('username', sa.String(length=130), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('history', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Users_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_Users_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Users_username'))
        batch_op.drop_index(batch_op.f('ix_Users_name'))

    op.drop_table('Users')
    with op.batch_alter_table('Products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Products_year'))
        batch_op.drop_index(batch_op.f('ix_Products_producer'))
        batch_op.drop_index(batch_op.f('ix_Products_name_prod'))
        batch_op.drop_index(batch_op.f('ix_Products_genre'))

    op.drop_table('Products')
    # ### end Alembic commands ###
