"""empty message

Revision ID: c630a6a10f49
Revises: a0d99b0bc1c7
Create Date: 2023-05-11 22:53:57.455761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c630a6a10f49'
down_revision = 'a0d99b0bc1c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genre', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_Products_genre'), ['genre'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Products_genre'))
        batch_op.drop_column('genre')

    # ### end Alembic commands ###
